/**
 * resourceData.js - Resource Definitions
 * 
 * This file contains the complete definition for every resource type.
 * Resources are the core economy elements of the game.
 */

const RESOURCE_DATA = {
    // =========================================
    // BASIC RESOURCES
    // =========================================
    food: {
        displayName: 'Food',
        icon: '🍖',
        category: 'basic',
        baseCapacity: 50,
        startingAmount: 10,
        description: 'Keeps your population alive. Citizens consume food daily.'
    },

    wood: {
        displayName: 'Wood',
        icon: '🪵',
        category: 'basic',
        baseCapacity: 100,
        startingAmount: 50,
        description: 'Basic building material gathered from forests.'
    },

    stone: {
        displayName: 'Stone',
        icon: '🪨',
        category: 'basic',
        baseCapacity: 50,
        startingAmount: 5,
        description: 'Durable building material from quarries and mines.'
    },

    metal: {
        displayName: 'Metal',
        icon: '⛏️',
        category: 'basic',
        baseCapacity: 50,
        startingAmount: 0,
        description: 'Raw ore extracted from mines, used for tools and weapons.'
    },

    // =========================================
    // PROCESSED RESOURCES
    // =========================================
    planks: {
        displayName: 'Planks',
        icon: '📐',
        category: 'processed',
        baseCapacity: 50,
        startingAmount: 0,
        description: 'Refined wood from lumber mills, needed for advanced construction.'
    },

    tools: {
        displayName: 'Tools',
        icon: '🔧',
        category: 'processed',
        baseCapacity: 50,
        startingAmount: 0,
        description: 'Equipment that improves worker efficiency.'
    },

    weapons: {
        displayName: 'Weapons',
        icon: '⚔️',
        category: 'processed',
        baseCapacity: 50,
        startingAmount: 0,
        description: 'Arms for your military forces.'
    },

    production: {
        displayName: 'Production',
        icon: '⚙️',
        category: 'processed',
        baseCapacity: 50,
        startingAmount: 0,
        description: 'Industrial capacity from workshops.'
    },

    // =========================================
    // CURRENCY
    // =========================================
    gold: {
        displayName: 'Gold',
        icon: '💰',
        category: 'currency',
        baseCapacity: 100,
        startingAmount: 0,
        description: 'The primary currency. Used for trading and upkeep.'
    },

    // =========================================
    // SPECIAL RESOURCES
    // =========================================
    research: {
        displayName: 'Research',
        icon: '🔬',
        category: 'special',
        baseCapacity: 100,
        startingAmount: 0,
        description: 'Knowledge points generated by scholars.'
    },

    training: {
        displayName: 'Training',
        icon: '🎯',
        category: 'special',
        baseCapacity: 100,
        startingAmount: 0,
        description: 'Military training progress.'
    },

    tactics: {
        displayName: 'Tactics',
        icon: '📜',
        category: 'special',
        baseCapacity: 100,
        startingAmount: 0,
        description: 'Strategic knowledge for military operations.'
    },

    mana: {
        displayName: 'Mana',
        icon: '✨',
        category: 'special',
        baseCapacity: 100,
        startingAmount: 0,
        description: 'Magical energy for arcane arts (coming soon).'
    },

    faith: {
        displayName: 'Faith',
        icon: '🙏',
        category: 'special',
        baseCapacity: 100,
        startingAmount: 0,
        description: 'Religious devotion from temples.'
    }
};

/**
 * Resource categories for UI organization
 */
const RESOURCE_CATEGORIES = {
    basic: {
        name: 'Basic Resources',
        order: 0,
        showInMainUI: true
    },
    processed: {
        name: 'Processed Goods',
        order: 1,
        showInMainUI: true
    },
    currency: {
        name: 'Currency',
        order: 2,
        showInMainUI: true
    },
    special: {
        name: 'Special',
        order: 3,
        showInMainUI: false
    }
};

// Export
window.RESOURCE_DATA = RESOURCE_DATA;
window.RESOURCE_CATEGORIES = RESOURCE_CATEGORIES;

console.log('[ResourceData] Resource definitions loaded');
